// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/budget_model.dart';
import 'data/models/expense_model.dart';
import 'data/models/income_model.dart';
import 'data/models/user_category_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 81247634925384840),
    name: 'Budget',
    lastPropertyId: const obx_int.IdUid(10, 6988449071697347134),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6510363472607288521),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 246579353552254622),
        name: 'uuid',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 333496852605170742),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3121793599520404564),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6198282910203467533),
        name: 'periodIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8526747932628606350),
        name: 'startDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5634995161435591799),
        name: 'endDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 499660993621569982),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4401545225109218369),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1105721272587349487),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6988449071697347134),
        name: 'title',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 739067201194216546),
    name: 'Expense',
    lastPropertyId: const obx_int.IdUid(14, 990660789136097827),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7479706554208144328),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2940436087485513663),
        name: 'uuid',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 7684636022723500697),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1800047645681547632),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7878583720816409208),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 249318011635223086),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1543650949294280813),
        name: 'categoryIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8776865924080066574),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1455796930493397699),
        name: 'paymentMethod',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4192989828849925450),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7365941715385902777),
        name: 'customCategoryUuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5200336887223575820),
        name: 'customCategoryName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 2782679574075699713),
        name: 'customCategoryColorValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6010590442099476674),
        name: 'customCategoryIconCodePoint',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 990660789136097827),
        name: 'customCategoryIconFontFamily',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 7534537932749283974),
    name: 'Income',
    lastPropertyId: const obx_int.IdUid(9, 9093734368351599795),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 407559700923601184),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5013365351290766669),
        name: 'uuid',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(6, 6203993762936950393),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7342506963534845692),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2014358193606310980),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4709049015137708348),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5100157389212553420),
        name: 'categoryIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3766088310270361795),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6410935936453824060),
        name: 'source',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 9093734368351599795),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 4144893094494599026),
    name: 'UserCategory',
    lastPropertyId: const obx_int.IdUid(10, 4298117351285369764),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3314709630581406443),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6648677548663915945),
        name: 'uuid',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(7, 7721961223379734638),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9182622049072066739),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8265655068231453351),
        name: 'typeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5414667479545639482),
        name: 'iconCodePoint',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4502809608429993445),
        name: 'iconFontFamily',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6352591594616012320),
        name: 'colorValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3823458794606573811),
        name: 'isDeleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3936056188928035010),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4298117351285369764),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(7, 4144893094494599026),
    lastIndexId: const obx_int.IdUid(7, 7721961223379734638),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      1386435878457391709,
      4667250250272597199,
      8530910738154387533,
    ],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      4286248834555536309,
      8201299129727239372,
      2588423017779414273,
      4067201059480405127,
      7747404916808867456,
      5882767399302189665,
      868554118677768587,
      7251540454158036757,
      8737047782863942502,
      8926470496389535023,
      6005398066568197137,
      8426471651077318668,
      2023289715859698165,
      160074701273853127,
      476365427094538494,
      5229508165175136115,
      2013005097154119909,
      1414350139442935485,
      7544111559829825367,
      7580535854297647677,
      7266669356714285421,
      574415832587173121,
      6634070900413190953,
      7406951788279076765,
      5615406809933684389,
      9047599874853163601,
      2223034359026450276,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Budget: obx_int.EntityDefinition<Budget>(
      model: _entities[0],
      toOneRelations: (Budget object) => [],
      toManyRelations: (Budget object) => {},
      getId: (Budget object) => object.id,
      setId: (Budget object, int id) {
        object.id = id;
      },
      objectToFB: (Budget object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(11);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addOffset(1, uuidOffset);
        fbb.addFloat64(2, object.amount);
        fbb.addInt64(3, object.periodIndex);
        fbb.addInt64(4, object.startDate.millisecondsSinceEpoch);
        fbb.addInt64(5, object.endDate.millisecondsSinceEpoch);
        fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(7, object.updatedAt.millisecondsSinceEpoch);
        fbb.addBool(8, object.isActive);
        fbb.addOffset(9, titleOffset);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Budget()
          ..id = const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4)
          ..uuid = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..amount = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            8,
            0,
          )
          ..periodIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..startDate = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
          )
          ..endDate = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
          )
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
          )
          ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
          )
          ..isActive = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            20,
            false,
          )
          ..title = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 22, '');

        return object;
      },
    ),
    Expense: obx_int.EntityDefinition<Expense>(
      model: _entities[1],
      toOneRelations: (Expense object) => [],
      toManyRelations: (Expense object) => {},
      getId: (Expense object) => object.id,
      setId: (Expense object, int id) {
        object.id = id;
      },
      objectToFB: (Expense object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final titleOffset = fbb.writeString(object.title);
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        final paymentMethodOffset = fbb.writeString(object.paymentMethod);
        final customCategoryUuidOffset = object.customCategoryUuid == null
            ? null
            : fbb.writeString(object.customCategoryUuid!);
        final customCategoryNameOffset = object.customCategoryName == null
            ? null
            : fbb.writeString(object.customCategoryName!);
        final customCategoryIconFontFamilyOffset =
            object.customCategoryIconFontFamily == null
            ? null
            : fbb.writeString(object.customCategoryIconFontFamily!);
        fbb.startTable(15);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addFloat64(3, object.amount);
        fbb.addInt64(4, object.date.millisecondsSinceEpoch);
        fbb.addInt64(5, object.categoryIndex);
        fbb.addOffset(6, notesOffset);
        fbb.addOffset(7, paymentMethodOffset);
        fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(9, customCategoryUuidOffset);
        fbb.addOffset(10, customCategoryNameOffset);
        fbb.addInt64(11, object.customCategoryColorValue);
        fbb.addInt64(12, object.customCategoryIconCodePoint);
        fbb.addOffset(13, customCategoryIconFontFamilyOffset);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Expense()
          ..id = const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4)
          ..uuid = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..title = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..amount = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..date = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
          )
          ..categoryIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            14,
            0,
          )
          ..notes = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 16)
          ..paymentMethod = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 18, '')
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
          )
          ..customCategoryUuid = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 22)
          ..customCategoryName = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 24)
          ..customCategoryColorValue = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            26,
          )
          ..customCategoryIconCodePoint = const fb.Int64Reader()
              .vTableGetNullable(buffer, rootOffset, 28)
          ..customCategoryIconFontFamily = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 30);

        return object;
      },
    ),
    Income: obx_int.EntityDefinition<Income>(
      model: _entities[2],
      toOneRelations: (Income object) => [],
      toManyRelations: (Income object) => {},
      getId: (Income object) => object.id,
      setId: (Income object, int id) {
        object.id = id;
      },
      objectToFB: (Income object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final titleOffset = fbb.writeString(object.title);
        final notesOffset = object.notes == null
            ? null
            : fbb.writeString(object.notes!);
        final sourceOffset = fbb.writeString(object.source);
        fbb.startTable(10);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addFloat64(3, object.amount);
        fbb.addInt64(4, object.date.millisecondsSinceEpoch);
        fbb.addInt64(5, object.categoryIndex);
        fbb.addOffset(6, notesOffset);
        fbb.addOffset(7, sourceOffset);
        fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Income()
          ..id = const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4)
          ..uuid = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..title = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..amount = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..date = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
          )
          ..categoryIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            14,
            0,
          )
          ..notes = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 16)
          ..source = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 18, '')
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
          );

        return object;
      },
    ),
    UserCategory: obx_int.EntityDefinition<UserCategory>(
      model: _entities[3],
      toOneRelations: (UserCategory object) => [],
      toManyRelations: (UserCategory object) => {},
      getId: (UserCategory object) => object.id,
      setId: (UserCategory object, int id) {
        object.id = id;
      },
      objectToFB: (UserCategory object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        final iconFontFamilyOffset = object.iconFontFamily == null
            ? null
            : fbb.writeString(object.iconFontFamily!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addInt64(3, object.typeIndex);
        fbb.addInt64(4, object.iconCodePoint);
        fbb.addOffset(5, iconFontFamilyOffset);
        fbb.addInt64(6, object.colorValue);
        fbb.addBool(7, object.isDeleted);
        fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(9, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = UserCategory()
          ..id = const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4)
          ..uuid = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..typeIndex = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..iconCodePoint = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            12,
          )
          ..iconFontFamily = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 14)
          ..colorValue = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            16,
            0,
          )
          ..isDeleted = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            18,
            false,
          )
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
          )
          ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
          );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Budget] entity fields to define ObjectBox queries.
class Budget_ {
  /// See [Budget.id].
  static final id = obx.QueryIntegerProperty<Budget>(
    _entities[0].properties[0],
  );

  /// See [Budget.uuid].
  static final uuid = obx.QueryStringProperty<Budget>(
    _entities[0].properties[1],
  );

  /// See [Budget.amount].
  static final amount = obx.QueryDoubleProperty<Budget>(
    _entities[0].properties[2],
  );

  /// See [Budget.periodIndex].
  static final periodIndex = obx.QueryIntegerProperty<Budget>(
    _entities[0].properties[3],
  );

  /// See [Budget.startDate].
  static final startDate = obx.QueryDateProperty<Budget>(
    _entities[0].properties[4],
  );

  /// See [Budget.endDate].
  static final endDate = obx.QueryDateProperty<Budget>(
    _entities[0].properties[5],
  );

  /// See [Budget.createdAt].
  static final createdAt = obx.QueryDateProperty<Budget>(
    _entities[0].properties[6],
  );

  /// See [Budget.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Budget>(
    _entities[0].properties[7],
  );

  /// See [Budget.isActive].
  static final isActive = obx.QueryBooleanProperty<Budget>(
    _entities[0].properties[8],
  );

  /// See [Budget.title].
  static final title = obx.QueryStringProperty<Budget>(
    _entities[0].properties[9],
  );
}

/// [Expense] entity fields to define ObjectBox queries.
class Expense_ {
  /// See [Expense.id].
  static final id = obx.QueryIntegerProperty<Expense>(
    _entities[1].properties[0],
  );

  /// See [Expense.uuid].
  static final uuid = obx.QueryStringProperty<Expense>(
    _entities[1].properties[1],
  );

  /// See [Expense.title].
  static final title = obx.QueryStringProperty<Expense>(
    _entities[1].properties[2],
  );

  /// See [Expense.amount].
  static final amount = obx.QueryDoubleProperty<Expense>(
    _entities[1].properties[3],
  );

  /// See [Expense.date].
  static final date = obx.QueryDateProperty<Expense>(
    _entities[1].properties[4],
  );

  /// See [Expense.categoryIndex].
  static final categoryIndex = obx.QueryIntegerProperty<Expense>(
    _entities[1].properties[5],
  );

  /// See [Expense.notes].
  static final notes = obx.QueryStringProperty<Expense>(
    _entities[1].properties[6],
  );

  /// See [Expense.paymentMethod].
  static final paymentMethod = obx.QueryStringProperty<Expense>(
    _entities[1].properties[7],
  );

  /// See [Expense.createdAt].
  static final createdAt = obx.QueryDateProperty<Expense>(
    _entities[1].properties[8],
  );

  /// See [Expense.customCategoryUuid].
  static final customCategoryUuid = obx.QueryStringProperty<Expense>(
    _entities[1].properties[9],
  );

  /// See [Expense.customCategoryName].
  static final customCategoryName = obx.QueryStringProperty<Expense>(
    _entities[1].properties[10],
  );

  /// See [Expense.customCategoryColorValue].
  static final customCategoryColorValue = obx.QueryIntegerProperty<Expense>(
    _entities[1].properties[11],
  );

  /// See [Expense.customCategoryIconCodePoint].
  static final customCategoryIconCodePoint = obx.QueryIntegerProperty<Expense>(
    _entities[1].properties[12],
  );

  /// See [Expense.customCategoryIconFontFamily].
  static final customCategoryIconFontFamily = obx.QueryStringProperty<Expense>(
    _entities[1].properties[13],
  );
}

/// [Income] entity fields to define ObjectBox queries.
class Income_ {
  /// See [Income.id].
  static final id = obx.QueryIntegerProperty<Income>(
    _entities[2].properties[0],
  );

  /// See [Income.uuid].
  static final uuid = obx.QueryStringProperty<Income>(
    _entities[2].properties[1],
  );

  /// See [Income.title].
  static final title = obx.QueryStringProperty<Income>(
    _entities[2].properties[2],
  );

  /// See [Income.amount].
  static final amount = obx.QueryDoubleProperty<Income>(
    _entities[2].properties[3],
  );

  /// See [Income.date].
  static final date = obx.QueryDateProperty<Income>(_entities[2].properties[4]);

  /// See [Income.categoryIndex].
  static final categoryIndex = obx.QueryIntegerProperty<Income>(
    _entities[2].properties[5],
  );

  /// See [Income.notes].
  static final notes = obx.QueryStringProperty<Income>(
    _entities[2].properties[6],
  );

  /// See [Income.source].
  static final source = obx.QueryStringProperty<Income>(
    _entities[2].properties[7],
  );

  /// See [Income.createdAt].
  static final createdAt = obx.QueryDateProperty<Income>(
    _entities[2].properties[8],
  );
}

/// [UserCategory] entity fields to define ObjectBox queries.
class UserCategory_ {
  /// See [UserCategory.id].
  static final id = obx.QueryIntegerProperty<UserCategory>(
    _entities[3].properties[0],
  );

  /// See [UserCategory.uuid].
  static final uuid = obx.QueryStringProperty<UserCategory>(
    _entities[3].properties[1],
  );

  /// See [UserCategory.name].
  static final name = obx.QueryStringProperty<UserCategory>(
    _entities[3].properties[2],
  );

  /// See [UserCategory.typeIndex].
  static final typeIndex = obx.QueryIntegerProperty<UserCategory>(
    _entities[3].properties[3],
  );

  /// See [UserCategory.iconCodePoint].
  static final iconCodePoint = obx.QueryIntegerProperty<UserCategory>(
    _entities[3].properties[4],
  );

  /// See [UserCategory.iconFontFamily].
  static final iconFontFamily = obx.QueryStringProperty<UserCategory>(
    _entities[3].properties[5],
  );

  /// See [UserCategory.colorValue].
  static final colorValue = obx.QueryIntegerProperty<UserCategory>(
    _entities[3].properties[6],
  );

  /// See [UserCategory.isDeleted].
  static final isDeleted = obx.QueryBooleanProperty<UserCategory>(
    _entities[3].properties[7],
  );

  /// See [UserCategory.createdAt].
  static final createdAt = obx.QueryDateProperty<UserCategory>(
    _entities[3].properties[8],
  );

  /// See [UserCategory.updatedAt].
  static final updatedAt = obx.QueryDateProperty<UserCategory>(
    _entities[3].properties[9],
  );
}
